name: Build and Deploy NodeJS

on:

  push:

    branches:

      - main



permissions:

  id-token: write

  contents: read



env:

  IMAGE_NAME: nodejs-demo



jobs:

  build:



    runs-on: ubuntu-latest



    steps:



      - name: Checkout Source

        uses: actions/checkout@v4



      - name: Azure Login (OIDC)

        uses: azure/login@v2

        with:

          client-id: ${{ secrets.AZURE_CLIENT_ID }}

          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}



    #   - name: Login to Azure Container Registry

    #     run: |

    #       az acr login --name ${{ secrets.ACR_NAME }}



    #   - name: Build Docker Image

    #     run: |

    #       docker build \

    #       -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }} \

    #       -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest .



    #   - name: Push Docker Image

    #     run: |

    #       docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    #       docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest



    #   - name: Update Azure Container App

    #     run: |

    #       az containerapp update \

    #         --name ${{ secrets.CONTAINER_APP_NAME }} \

    #         --resource-group ${{ secrets.RESOURCE_GROUP }} \

    #         --image ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
